"""add match validation system

Revision ID: 31f72b3f4050
Revises: 466a3db616a7
Create Date: 2026-06-11 09:14:15.034438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f72b3f4050'
down_revision = '466a3db616a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_by_profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_by_profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_by_profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'player_profiles', ['confirmed_by_profile_id'], ['id'])
        batch_op.create_foreign_key(None, 'player_profiles', ['rejected_by_profile_id'], ['id'])
        batch_op.create_foreign_key(None, 'player_profiles', ['submitted_by_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('rejected_by_profile_id')
        batch_op.drop_column('confirmed_by_profile_id')
        batch_op.drop_column('submitted_by_profile_id')

    # ### end Alembic commands ###
