"""Add STC payment fields

Revision ID: 490488b36fa9
Revises: fdc24e511d7d
Create Date: 2026-07-29 12:38:51.161437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490488b36fa9'
down_revision = 'fdc24e511d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.drop_column('paid_at')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
