"""add open matches

Revision ID: c2d11261ad5b
Revises: 9af4e22baf13
Create Date: 2026-06-23 14:47:26.343947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d11261ad5b'
down_revision = '9af4e22baf13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('club', sa.String(length=120), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('match_time', sa.Time(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('team_a_player_1_id', sa.Integer(), nullable=True),
    sa.Column('team_a_player_2_id', sa.Integer(), nullable=True),
    sa.Column('team_b_player_1_id', sa.Integer(), nullable=True),
    sa.Column('team_b_player_2_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_a_player_1_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['team_a_player_2_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['team_b_player_1_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['team_b_player_2_id'], ['player_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_match_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_match_id', sa.Integer(), nullable=False),
    sa.Column('player_profile_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['open_match_id'], ['open_matches.id'], ),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_match_players')
    op.drop_table('open_matches')
    # ### end Alembic commands ###
