"""add terms and privacy acceptance to users

Revision ID: fdc24e511d7d
Revises: 3fe17f8bef13
Create Date: 2026-06-26 15:24:31.640124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc24e511d7d'
down_revision = '3fe17f8bef13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('privacy_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('privacy_accepted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('privacy_accepted_at')
        batch_op.drop_column('privacy_accepted')
        batch_op.drop_column('terms_accepted_at')
        batch_op.drop_column('terms_accepted')

    # ### end Alembic commands ###
